# Generated by Django 5.2.10 on 2026-02-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_type',
            field=models.CharField(choices=[('f', 'Oziq-ovqat')], default='f', max_length=1),
        ),
    ]
