# Generated by Django 5.2.10 on 2026-02-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_good_category_alter_good_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='product.productitem'),
        ),
    ]
