# Generated by Django 5.2.10 on 2026-02-12 15:28

import apps.merchant.models
import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.BigIntegerField(blank=True, default=0, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'BankCardModel',
                'verbose_name_plural': 'BankCardModels',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reminder', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reminder_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reminder_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reminder_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reminder_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('agreement', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('agreement_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('agreement_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('agreement_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('agreement_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipment_terms', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipment_terms_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipment_terms_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipment_terms_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipment_terms_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_us_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('support_center', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('support_center_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('support_center_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('support_center_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('support_center_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('payment_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('payment_data_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('payment_data_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('payment_data_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('payment_data_ko', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('imo', models.CharField(blank=True, max_length=255, null=True)),
                ('kakao', models.CharField(blank=True, max_length=255, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('cycle_days', models.PositiveIntegerField(default=60)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_card', to='customer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.merchant.models.generate_order_number, editable=False, max_length=10, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_cart', 'Savatchada'), ('pending', "Admin tasdig'i kutilmoqda"), ('payment_pending', "To'lov kutilmoqda"), ('approved', 'Tasdiqlandi'), ('cancelled', 'Bekor qilindi'), ('Sent', 'Yetkazildi')], default='in_cart', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('loyalty_payment', models.IntegerField(blank=True, default=0, null=True)),
                ('bankcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_card', to='merchant.bankcardmodel')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPendingBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255)),
                ('order_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('percent', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.profile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bonus', to='merchant.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='merchant.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='product.productitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', through='merchant.OrderItem', to='product.productitem'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rewarded', 'Rewarded'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='customer.profile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='customer.profile')),
            ],
            options={
                'unique_together': {('referrer', 'referee')},
            },
        ),
    ]
